// <auto-generated />
namespace PlayTime.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddRegistrationAdjustments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRegistrationAdjustments));
        
        string IMigrationMetadata.Id
        {
            get { return "201412080958559_AddRegistrationAdjustments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
