//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayTime.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_Registration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_Registration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlayTime.Web.Resources.Registration", typeof(Resources_Registration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        public static string Button_CreateNew {
            get {
                return ResourceManager.GetString("Button_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string FieldLabel_CustomerId {
            get {
                return ResourceManager.GetString("FieldLabel_CustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        public static string FieldLabel_EndTime {
            get {
                return ResourceManager.GetString("FieldLabel_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string FieldLabel_Note {
            get {
                return ResourceManager.GetString("FieldLabel_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string FieldLabel_ProjectId {
            get {
                return ResourceManager.GetString("FieldLabel_ProjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string FieldLabel_StartTime {
            get {
                return ResourceManager.GetString("FieldLabel_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string FieldLabel_TaskId {
            get {
                return ResourceManager.GetString("FieldLabel_TaskId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a customer.
        /// </summary>
        public static string FieldRequired_CustomerId {
            get {
                return ResourceManager.GetString("FieldRequired_CustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to enter an end time.
        /// </summary>
        public static string FieldRequired_EndTime {
            get {
                return ResourceManager.GetString("FieldRequired_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to enter a note.
        /// </summary>
        public static string FieldRequired_Note {
            get {
                return ResourceManager.GetString("FieldRequired_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a project.
        /// </summary>
        public static string FieldRequired_ProjectId {
            get {
                return ResourceManager.GetString("FieldRequired_ProjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to enter a start time.
        /// </summary>
        public static string FieldRequired_StartTime {
            get {
                return ResourceManager.GetString("FieldRequired_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a task.
        /// </summary>
        public static string FieldRequired_TaskId {
            get {
                return ResourceManager.GetString("FieldRequired_TaskId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no registrations....
        /// </summary>
        public static string Message_NoData {
            get {
                return ResourceManager.GetString("Message_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrations.
        /// </summary>
        public static string PageTitle_Registration_Index {
            get {
                return ResourceManager.GetString("PageTitle_Registration_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Table_Customer {
            get {
                return ResourceManager.GetString("Table_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Table_Delete {
            get {
                return ResourceManager.GetString("Table_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Table_Edit {
            get {
                return ResourceManager.GetString("Table_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        public static string Table_EndTime {
            get {
                return ResourceManager.GetString("Table_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is invoiced?.
        /// </summary>
        public static string Table_IsInvoiced {
            get {
                return ResourceManager.GetString("Table_IsInvoiced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Table_Note {
            get {
                return ResourceManager.GetString("Table_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Table_Project {
            get {
                return ResourceManager.GetString("Table_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string Table_StartTime {
            get {
                return ResourceManager.GetString("Table_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string Table_Task {
            get {
                return ResourceManager.GetString("Table_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time spent.
        /// </summary>
        public static string Table_TimeSpent {
            get {
                return ResourceManager.GetString("Table_TimeSpent", resourceCulture);
            }
        }
    }
}
